/**
 * Merges Capability Index rows from multiple SKILL.md files into a unified top-level SKILL.md.
 * Idempotent: re-running with the same skills does not duplicate rows.
 */

export interface CapabilityRow {
  userNeed: string;
  capability: string;
  instructions: string;
  sourceSkill: string;
}

const SECTION_HEADER = "## Capability Index";
const TABLE_HEADER = "| User Need | Capability | Detailed Instructions |";
const TABLE_DIVIDER = "|-----------|-----------|----------------------|";

/** Parse capability rows from a SKILL.md string. */
export function parseCapabilityRows(content: string, sourceSkill: string): CapabilityRow[] {
  const rows: CapabilityRow[] = [];
  const lines = content.split("\n");

  let inTable = false;
  for (const line of lines) {
    if (line.startsWith(TABLE_HEADER)) {
      inTable = true;
      continue;
    }
    if (inTable && line.startsWith("|---")) continue;
    if (inTable && line.startsWith("|")) {
      const cols = line.split("|").slice(1, -1).map((c) => c.trim());
      if (cols.length >= 3) {
        rows.push({
          userNeed: cols[0],
          capability: cols[1],
          instructions: cols[2],
          sourceSkill,
        });
      }
    } else if (inTable) {
      // end of table
      inTable = false;
    }
  }
  return rows;
}

/** Deduplicate rows by capability name (case-insensitive). */
export function deduplicateRows(rows: CapabilityRow[]): CapabilityRow[] {
  const seen = new Map<string, CapabilityRow>();
  for (const row of rows) {
    const key = row.capability.toLowerCase();
    if (!seen.has(key)) {
      seen.set(key, row);
    }
  }
  return Array.from(seen.values());
}

/** Render rows into a markdown Capability Index table. */
export function renderCapabilityTable(rows: CapabilityRow[]): string {
  const lines = [
    SECTION_HEADER,
    "",
    TABLE_HEADER,
    TABLE_DIVIDER,
    ...rows.map(
      (r) => `| ${r.userNeed} | ${r.capability} | ${r.instructions} |`
    ),
    "",
    `> Generated by pharos-skills CLI. Sources: ${[...new Set(rows.map((r) => r.sourceSkill))].join(", ")}`,
  ];
  return lines.join("\n");
}

/** Build merged SKILL.md content from multiple skill SKILL.md files. */
export function mergeSkillMd(
  installedSkills: Array<{ name: string; content: string }>
): string {
  const allRows: CapabilityRow[] = [];

  for (const { name, content } of installedSkills) {
    const rows = parseCapabilityRows(content, name);
    allRows.push(...rows);
  }

  const uniqueRows = deduplicateRows(allRows);
  const skillNames = installedSkills.map((s) => s.name).join(", ");

  return `---
name: pharos-skills
description: Unified Pharos Skills entry point. Aggregates capabilities from: ${skillNames}.
---

# Pharos Skills

Installed skills: **${skillNames}**

Read \`shared/references/_guardrails.md\` before any operation.
Network config: \`shared/assets/networks.json\`. Default: Atlantic Testnet (chainId 688689).

${renderCapabilityTable(uniqueRows)}

## Next Steps

1. Install Foundry if needed: \`curl -L https://foundry.paradigm.xyz | bash && foundryup\`
2. Export private key: \`export PRIVATE_KEY=0x...\` (from env or gitignored file)
3. Set RPC: \`export RPC_URL=https://atlantic.dplabs-internal.com\`
4. For x402: copy \`.pharos/skills/pharos-x402-payments/assets/.env.example\` to \`.env\` and configure.
`;
}
